#include<stdio.h>
#include<conio.h>
#include<graphics.h>
void main()
{
int gdriver=DETECT,gmode;
float xc,yc,rx,ry,x,y,p,p1;
initgraph(&gdriver,&gmode,"C:\\TC\\BGI");
setbkcolor(BLACK);
printf("Enter Centre:\n");
scanf("%f%f",&rx,&ry);
x=0;
y=ry;
p=(ry*ry)-(rx*rx*ry)+((1/4)*(rx*rx));
while((2*ry*ry*x)<(2*rx*rx*y))
{
p=p1;
putpixel((int)xc+x,(int)yc+y,WHITE);
putpixel((int)xc-x,(int)yc+y,WHITE);
putpixel((int)xc-x,(int)yc-y,WHITE);
putpixel((int)xc+x,(int)yc-y,WHITE);
if(p<0)
{
x=x+1;
p1=p+(2*ry*ry*x)+(ry*ry);
}
else
{
x=x+1;
y=y-1;
p1=p+((2*ry*ry*x)-(2*rx*rx*y)+(ry*ry));
}
}
p=((x+0.5)*ry*ry)+((y-1)*rx*rx)-(rx*rx*ry*ry);
while(y!=0)
{
p=p+1;
putpixel((int)xc+x,(int)yc+y,WHITE);
putpixel((int)xc-x,(int)yc+y,WHITE);
putpixel((int)xc-x,(int)yc-y,WHITE);
putpixel((int)xc+x,(int)yc-y,WHITE);
if(p>0)
{
y=y-1;
p1=p-((2*rx*rx)*y)+(rx*rx);
}
else
{
x=x+1;
y=y-1;
p1=p+((2*ry*ry)*x)-((2*rx*rx)*y)+(rx*rx);
}
}
line(xc+rx,yc,xc-rx,yc);
line(xc,yc+ry,xc,yc-ry);
getch();
closegraph();
}
